#name: Auto Tag & Release
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  tag-and-release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Check commit message and extract version
#        id: get_version
#        run: |
#          MSG="$(git log -1 --pretty=%B)"
#          if [[ "$MSG" =~ ^version[[:space:]]([0-9]+\.[0-9]+)$ ]]; then
#            VERSION="v${BASH_REMATCH[1]}"
#            echo "version=$VERSION" >> $GITHUB_OUTPUT
#          else
#            echo "No version bump commit, skipping."
#            exit 0
#          fi
#      - name: Create Tag
#        if: steps.get_version.outputs.version != ''
#        env:
#          GH_PAT: ${{ secrets.GH_PAT }}
#        run: |
#          echo ${#GH_PAT}
#          git config --global user.name "luiox"
#          git config --global user.email "1517807724@qq.com"
#          git tag ${{ steps.get_version.outputs.version }}
#          echo "echo $GH_PAT" > askpass.sh
#          chmod +x askpass.sh
#          GIT_ASKPASS=$PWD/askpass.sh git push https://github.com/${{ github.repository }}.git ${{ steps.get_version.outputs.version }}
#      - name: Create GitHub Release
#        if: steps.get_version.outputs.version != ''
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ steps.get_version.outputs.version }}
#          generate_release_notes: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
